### ISSUE TITLE
Compile errors in 2019.2.2f1

### ISSUE THREAD

**Issue by zsculpt** [ArthurBrussee/Vapor#8]
Calls to UnityEngine.Rendering.PostProcessing.RuntimeUtilities.BlitFullscreenTriangle, and UnityEngine.Rendering.PostProcessing.RuntimeUtilities.GetAttribute are ambiguous:

Assets\Vapor-master\Examples\PostProcessing\Runtime\Monitors\WaveformMonitor.cs(89,17): error CS0121: The call is ambiguous between the following methods or properties: 'UnityEngine.Rendering.PostProcessing.RuntimeUtilities.BlitFullscreenTriangle(UnityEngine.Rendering.CommandBuffer, UnityEngine.Rendering.RenderTargetIdentifier, UnityEngine.Rendering.RenderTargetIdentifier, bool)' and 'UnityEngine.Rendering.PostProcessing.RuntimeUtilities.BlitFullscreenTriangle(UnityEngine.Rendering.CommandBuffer, UnityEngine.Rendering.RenderTargetIdentifier, UnityEngine.Rendering.RenderTargetIdentifier, bool, UnityEngine.Rect?)'

**Comment by ArthurBrussee** [comment]
Now that post processing is a package, I've removed the post effects from the examples. Also slims down the package. 

Let me know if it still doesn't work in 2019.2!
