### ISSUE TITLE
Doesn't work in 2017.3

### ISSUE THREAD

**Issue by k0091601** [ArthurBrussee/Vapor#4]
Doesn't render correctly in 2017.3, in a vanilla install.
Looks like final blend with scene pass is missing or broken.

**Comment by ArthurBrussee** [comment]
Seems to work for me in 2017.3 - are you in forward or deferred? In forward - did you enable vapor in your shaders?

**Comment by k0091601** [comment]
I'm just trying to launch either of the example scenes and they both fail with;
Assets/Examples/PostProcessing/Runtime/Effects/TemporalAntialiasing.cs(127,55): error CS0117: `UnityEngine.Rendering.PostProcessing.RuntimeUtilities' does not contain a definition for `GenerateJitteredProjectionMatrixFromOriginal'

**Comment by Wyattari** [comment]
I got the same error as @k0091601. Once I commented out that code it worked, but I'm getting massive streaking. Also only getting about 60fps in the demo scenes with deferred rendering, single stereo pass, a 980 ti and a Vive.

**Comment by iLoveYourFace** [comment]
@Wyattari End up finding a fix or alternative?

**Comment by Wyattari** [comment]
@iLoveYourFace Turns out the code I commented out is pretty necessary for stuff to work. I ended up getting decent results from https://github.com/raphael-ernaelsten/Aura - but we need to figure out how to get single stereo pass working.

**Comment by iLoveYourFace** [comment]
@Wyattari Yeah I'm using Aura with multi pass atm. Really need single pass!

**Comment by KPLBrock** [comment]
Can report that this still happens with Unity 2018.1 onwards. Same error, and uncommenting the code it can't find will just cause a crash.

**Comment by KPLBrock** [comment]
For reference,this is the error when trying to make this work:
```
Property (_GradientTextureBlend) at kernel index (0) is not set
UnityEngine.ComputeShader:Dispatch(Int32, Int32, Int32, Int32)
```

**Comment by theMaxscriptGuy** [comment]
Somehow the _GradientTextureBlend is just declared and not defined in VaporSim.compute.
if you comment the following lines, all works fine:

```
#if defined(BLEND)
	grad = lerp(grad, _GradientTextureBlend.SampleLevel(sampler_GradientTexture, gradientUv, 0), _SettingBlend);
#endif
```

**Comment by ArthurBrussee** [comment]
Hi all

Long radio silences, sorry about that. I will make it work in 2018.3+ today (or do people need older versions?)
